### PR TITLE
Fix #23 - fix some issues when SqueezeAmp doesn't have a display

### LINKED ISSUE #23: Make prefs conditional to prevent error being logged
On https://github.com/sle118/squeezelite-esp32/blob/4f324b90d7d0534b8bf0969467ab32cc0f1d5e57/plugin/SqueezeESP32/PlayerSettings.pm#L33 you define what prefs to handle in the player settings. But many of these are not define in the template unless you have a display connected. Therefore you should make these conditional:

```diff
diff --git a/plugin/SqueezeESP32/PlayerSettings.pm b/plugin/SqueezeESP32/PlayerSettings.pm
index 9b331d8..33c275a 100644
--- a/plugin/SqueezeESP32/PlayerSettings.pm
+++ b/plugin/SqueezeESP32/PlayerSettings.pm
@@ -30,7 +30,8 @@ sub page {
 
 sub prefs {
        my ($class, $client) = @_;
-       my @prefs = qw(width small_VU spectrum artwork eq);
+       my @prefs;
+       shift @prefs, qw(width small_VU spectrum artwork eq) if $client->displayWidth;
        return ($prefs->client($client), @prefs);
 }
```

### PR DESCRIPTION
**Pull request by michaelherger**
* only push simple prefs on the list of automatically managed items - hashes and lists can't be managed by the Settings super class
* only push display/artwork related prefs on the list if deal with a player which has a display
* move most artwork/display handling code out of the plugin to the Player class
* rename `eq` pref to `equalizer`, as `eq` is a reserved word
* automatically update the player when the `equalizer` pref is changed
* strip down Plugin to the bare minimum needed with any SqueezeAMP, no matter whether it has a display or not

### CODE REVIEW

**Comment by michaelherger** [comment]
Oops... my editor prefs "cleaned up" some whitespace. Make sure you configure the diff viewer to ignore whitespace only changes...

File: plugin/SqueezeESP32/Plugin.pm [hunk 1]
```diff
@@ -16,121 +14,84 @@ my $log = Slim::Utils::Log->addLogCategory({
...
 	$class->SUPER::initPlugin(@_);
 	Slim::Networking::Slimproto::addPlayerClass($class, 100, 'squeezeesp32', { client => 'Plugins::SqueezeESP32::Player', display => 'Plugins::SqueezeESP32::Graphics' });
-	$log->info("Added class 100 for SqueezeESP32");
-	
-	Slim::Control::Request::subscribe( sub { onNotification(@_) }, [ ['newmetadata'] ] );
-	Slim::Control::Request::subscribe( sub { onNotification(@_) }, [ ['playlist'], ['open', 'newsong'] ]);
+	main::INFOLOG && $log->is_info && $log->info("Added class 100 for SqueezeESP32");
+
+	Slim::Control::Request::subscribe( \&onNotification, [ ['newmetadata'] ] );
+	Slim::Control::Request::subscribe( \&onNotification, [ ['playlist'], ['open', 'newsong'] ]);
```
Comment (philippe44) [inline plugin/SqueezeESP32/Plugin.pm:47]: I don't understand, I thought we discussed that when there is no client, subscriptions with the same function overwrite each other
```
sub subscribe {
	my $subscriberFuncRef = shift || return;
	my $requestsRef = shift;
	my $client = shift;
	
	if ( blessed($client) ) {
		$listeners{ $client->id . $subscriberFuncRef } = [ __requestRE($requestsRef), $subscriberFuncRef, $requestsRef, $client->id ];
	}
	else {
		$listeners{$subscriberFuncRef} = [ __requestRE($requestsRef), $subscriberFuncRef, $requestsRef ];
	}
```

Comment (michaelherger) [reply plugin/SqueezeESP32/Plugin.pm:47]: I fear I'm too old to say "I only wanted to test whether you paid attention"... so... sorry, will fix that.

Comment (philippe44) [reply plugin/SqueezeESP32/Plugin.pm]: Well ... I pay attention to every change you make because they are opportunities for me to learn something

File: plugin/SqueezeESP32/PlayerSettings.pm [hunk 2]
```diff
@@ -30,63 +30,60 @@ sub page {
 
 sub prefs {
 	my ($class, $client) = @_;
-	my @prefs = qw(width small_VU spectrum artwork eq);
+	my @prefs;
+	push @prefs, qw(width small_VU) if $client->displayWidth;
 	return ($prefs->client($client), @prefs);
```
Comment (philippe44) [inline plugin/SqueezeESP32/PlayerSettings.pm:35]: So we don't need to set other prefs (the non-scalar ones) here as we do that in the handler?

Comment (michaelherger) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: Exactly. Actually you don't want them to be handled by the super class, as it might break things. As you've seen you had to read the prefs yourself anyway, because `Settings` wouldn't treat them correctly. Better take them in your hands and don't let that code touch them.

I never really looked into that code. But I must assume that LMS itself doesn't have many "complex" prefs. Or didn't back in the days. The base class is/was good for 9x% of the code, thus never enhanced this way.

Comment (philippe44) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: understood - thanks for the explanation

Comment (philippe44) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: I did some test this week-end as I was pushing the IR changes and if I don't set in @prefs  spectrum, artwork,and eq then there is nothing set in setting screen for these items. Then what is saved is 0/no value and that causes a div0 when updating. 
As said, I don't understand well this part of Settings, so I need to have a better look. It this an issue where beforeHandler would be required to set the prefs?

Comment (michaelherger) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: Oh, I believe I see what is missing: the template is accessing `prefs.pref_spectrum`, but you store the prefs in `pref_spectrum` etc. directly. I'll try to fix that.

Comment (michaelherger) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: Background being that the `Settings` base class would store prefs in the `prefs` element to make sure there are no naming conflicts with other items in the `$paramRef`.

Comment (michaelherger) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: See https://github.com/sle118/squeezelite-esp32/pull/27

Comment (philippe44) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: ok, I think I'm starting so understand this settings things. So every 'xxx' that is set through the "prefs" method will end up being stored in a "prefs." element, but not as prefs.xxx but as prefs.pref_xxx. But in paramsRef, they should still be addressed as paramsRef->{'ref_xxx'}.

Although, if you are not settings xxx in 'prefs' method, you can still use the paramsRef->
{'ref_xxx'} if you want to, but using the 'pref_' prefix is really useless, in my example I could have used 'spectrum' directly, it's just a better practice to avoid name conflict.

I guess what always confused me is the magic that the class does when a paramRef hash 'ref_xxx' exists *and* 'xxx' has been set in the 'prefs' method.

Comment (michaelherger) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: No, in `$paramsRef` they should still be addressed as `$paramsRef->{prefs}->{pref_xxx}`. But the thing is: if I want to deal with a pref in my code, then I'm not putting it on the list returned by the `prefs()` method. And in that case I can call it whatever I want, as long as I don't create a conflict. You'd also have to handle the pref yourself if it wasn't a simple scalar value. In that case, again, you can call it whatever you want. 

The issue I had created was that I _removed_ some prefs from the list dealt with by the super class, but the template relied on them being stored in `prefs.pref_xxx`. At the same time you set `$paramRef->{pref_xxx}`, which actually resulted in those prefs to be in `$paramRef` twice, once within the `prefs` attribute, and once outside. You modified and stored the latter, but the template read from the former. After I removed those prefs from the list dealt with automatically, `prefs.pref_xxx` was no longer set.

Comment (philippe44) [reply plugin/SqueezeESP32/PlayerSettings.pm:35]: understood I think. What confused me as well was that although I was setting paramRef->{pref_xxx} and getting the result from these as well (under savesettings), the access in the html was using prefs.pref_xxx. I assume that worked because they were both a reference to the same object, not copies. 
Similarly as the template toolkit let you use things like
``` 
	[% WRAPPER setting title="PLUGIN_SQUEEZEESP32_WIDTH" desc="PLUGIN_SQUEEZEESP32_WIDTH_DESC" %]
			<input type="hidden" name="pref_width" value="[% prefs.pref_width %]">
			[% prefs.pref_width %]
		[% END %]
```
Which got me confused about when the "pref_width" is "created" because I don't create it, it's only set in the methods "prefs". I think in the future I wont prefix my own (non-auto-managed) preferences by 'pref_' but by something else so that I don't forget. 
There are probably too much C muscle thinking in me (or not enough muscles :-)
